apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: exa-tester-assessment
  annotations:
    github.com/project-slug: emisgroup/exa-tester-assessment
spec:
  type: service
  lifecycle: production
  owner: group:default/nightingale-admin
